version: '3.1'
services:
  devbox:
    image: "aidbox/devbox:0.1.0"
    depends_on:
      - "devbox-db"
    links:
      - "devbox-db:database"
    ports:
      - "${DEVBOX_PORT:-8888}:8888"
    volumes:
      - ./config:/var/config
      - ./pgdata:/var/static
    environment:
      FILE_ROOT:     /var/static
      AIDBOX_CONFIG: /var/config/config.edn
      PORT:          8888
      PGHOST:        database
      PGPORT:        5432
      PGUSER:        postgres
      PGPASSWORD:    postgres
      PGDATABASE:    devbox
  devbox-db:
    image: "aidbox/aidboxdb:0.0.1-alpha3"
    volumes:
      - "./pgdata:/data"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox
