version: '3.1'
services:
  old-devbox-db:
    image: "${PG_OLD_IMAGE}"
    volumes:
      - "${PG_OLD_DATA}:/data"

  new-devbox-db:
    image: "${PG_IMAGE}"
    links:
      - old-devbox-db
    depends_on:
      - old-devbox-db
    volumes:
      - "${PG_DATA}:/data"
      - "./backup:/backup"
    environment:
      # cluster creds
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"
      # psql creds
      PGUSER:      "${PGUSER}"
      PGPASSWORD:  "${PGPASSWORD}"
      PGDATABASE:  "${PGDATABASE}"
