apiVersion: 1

datasources:
  - name: aidbox-logs
    type: elasticsearch
    access: proxy
    database: "*"
    url: http://es:9200
    jsonData:
      interval: Daily
      timeField: "ts"
      esVersion: "7.0.0"
      logMessageField: message
      logLevelField: fields.level
  - name: Prometheus
    #    uid: prom
    type: prometheus
    access: proxy
    database: "*"
    url: http://prometheus:9090
