apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  config.edn: {{ .Values.config | quote }}
