replicaCount: 1
image:
  repository: aidbox/aidboxdb
  tag: 0.0.1-alpha3
  pullPolicy: IfNotPresent

service:
  port: 5432

user: postgres
password: postgres
database: devbox

persistence:
  enabled: false
  type: "pvc"
  size: 20Gi
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
