apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          {{- if eq .Values.persistence.type "node" }}
          hostPath:
            path: /data/pgdata/{{ .Values.database }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ (include "fullname" .) }}
          {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: PGUSER
              value: {{ default "postgres" .Values.user | quote }}
            - name: POSTGRES_DB
              value: {{ default "" .Values.database | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ default "" .Values.password | quote }}
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 5432
          
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}

      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector }}
      {{- end }}
