ingress:
  enabled: false
  hosts:
    - host: my.host 
  annotations:
    ingress.kubernetes.io/proxy-body-size: 30m
    kubernetes.io/ingress.class: nginx

#resources:
#  requests:
#    cpu: "1"
#    memory: "1Gi"

aidboxdb:
  database: "devbox" 
  password: "postgres"
  user: "postgres"
  #nodeSelector:
  #  pg: master
  persistence:
    enabled: true 
    type: "pvc"
    size: 10Gi
#  resources:
#    requests:
#      cpu: "1"
#      memory: "1Gi"
