global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels: {monitor: aidbox}
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']
- job_name: pushgateway
  scrape_interval: 5s
  honor_labels: true
  static_configs:
  - targets: ['pushgateway:9091']
- job_name: aidbox
  scrape_interval: 5s
  metrics_path: /metrics
  static_configs:
  - targets: ['devbox:8080']
- job_name: aidbox-minutes
  scrape_interval: 30s
  metrics_path: /metrics/minutes
  static_configs:
  - targets: ['devbox:8080']
- job_name: aidbox-hours
  scrape_interval: 1m
  metrics_path: /metrics/hours
  static_configs:
  - targets: ['devbox:8080']
