{
 "title": "Performance Metrics (HAPI)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 }, "options": { "content": "# HAPI + Postgres" } },
  {
   "title": "request sum",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(30, sum(rate(perf_request_duration_sum{acount=~'.*'}[$__range])) by (acount))",
     "legendFormat": "{{acount}}"
    }
   ]
  },
  {
   "title": "req mean",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rate( perf_request_duration_sum{acount=~'.+'}[$__interval])/rate( perf_request_duration_count [$__interval]))",
     "legendFormat": "{{acount}}"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase( perf_request_duration_count [$__interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(rate(perf_request_count{threads='2'}[$__rate_interval])) [1h:])",
     "legendFormat": "2 threads"
    },
    {
     "expr": "max_over_time(sum(rate(perf_request_count{threads='4'}[$__rate_interval])) [1h:])",
     "legendFormat": "4 threads"
    },
    {
     "expr": "max_over_time(sum(rate(perf_request_count{threads='8'}[$__rate_interval])) [1h:])",
     "legendFormat": "8  threads"
    },
    {
     "expr": "max_over_time(sum(rate(perf_request_count{threads='16'}[$__rate_interval])) [1h:])",
     "legendFormat": "16 threads"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(perf_request_count[$__rate_interval])) by (threads)",
     "legendFormat": "{{threads}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(perf_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(perf_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(perf_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "75"
    },
    {
     "expr": "sum(rate(perf_request_duration_sum[$__rate_interval]))/sum(rate(perf_request_duration_count[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(perf_request_duration_count{status!~'2..'}[$__range])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}