{
 "title": "Performance Metrics (Aidbox)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum(rate(perf_request_count{threads='2'}[$__rate_interval])) [15m:])",
     "legendFormat": "2 threads"
    },
    {
     "expr": "max_over_time(sum(rate(perf_request_count{threads='4'}[$__rate_interval])) [15m:])",
     "legendFormat": "4 threads"
    },
    {
     "expr": "max_over_time(sum(rate(perf_request_count{threads='8'}[$__rate_interval])) [15m:])",
     "legendFormat": "8  threads"
    },
    {
     "expr": "max_over_time(sum(rate(perf_request_count{threads='16'}[$__rate_interval])) [15m:])",
     "legendFormat": "16 threads"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " max_over_time(sum(rate(aidbox_http_request_duration_seconds_count[$__rate_interval])) [5m:])",
     "legendFormat": "aidbox max rps"
    }
   ]
  },
  {
   "title": "Perf Test",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(rate(perf_request_count[$__rate_interval])) by (threads)",
     "legendFormat": "{{threads}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "box req"
    },
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_bucket{le=\"+Inf\"} [$__rate_interval])) - sum(rate(aidbox_http_request_duration_seconds_bucket{le=\"0.5\"} [$__rate_interval]))",
     "legendFormat": "> 0.5 sec"
    },
    {
     "expr": "rate(pg_requests_total[$__rate_interval])",
     "legendFormat": "db req"
    }
   ]
  },
  {
   "title": "Perf Test Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(perf_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(perf_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(perf_request_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "75"
    },
    {
     "expr": "sum(rate(perf_request_duration_sum[$__rate_interval]))/sum(rate(perf_request_duration_count[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aidbox_http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_sum[1m]))/sum(rate(aidbox_http_request_duration_seconds_count[1m]))",
     "legendFormat": "box avg"
    },
    {
     "expr": "rate(pg_requests_duration_seconds_sum[1m])/rate(pg_requests_total[1m])",
     "legendFormat": "db avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(aidbox_http_request_wait_seconds_bucket[1m])) by (le))",
     "legendFormat": "wait99"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(aidbox_http_request_wait_seconds_bucket[1m])) by (le))",
     "legendFormat": "wait75"
    },
    {
     "expr": "rate(hikari_acquire_wait_seconds_sum[1m])/rate(hikari_acquire_wait_seconds_count[1m])",
     "legendFormat": "hikari wait"
    }
   ]
  },
  {
   "title": "Perf Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(perf_request_duration_count{status!~'2..'}[$__range])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_count{status=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    },
    { "expr": "rate(hikari_timeout_total[5m])", "legendFormat": "db conn err" },
    {}
   ]
  },
  {
   "title": "req mean dist",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rate( perf_request_duration_sum{acount=~'.+'}[$__interval])/rate( perf_request_duration_count [$__interval]))",
     "legendFormat": "{{acount}}"
    }
   ]
  },
  {
   "title": "request dist",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(30, rate( perf_request_duration_sum [$__range]))",
     "legendFormat": "{{acount}}"
    }
   ]
  },
  {
   "title": "req mean dist",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rate(aidbox_http_request_duration_seconds_sum[$__interval])/rate(aidbox_http_request_duration_seconds_count[$__interval]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "request dist",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(30, rate(aidbox_http_request_duration_seconds_sum[$__range]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "resp statuses",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_count[30m]))  by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "jvm threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
   "targets": [
    { "expr": "jvm_thread_count", "legendFormat": "threads" },
    { "expr": "jvm_thread_peak_count", "legendFormat": "threads peak" },
    { "expr": "jvm_thread_daemon_count", "legendFormat": "daemon" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_heap_memory", "legendFormat": "heap" },
    { "expr": "jvm_non_heap_memory", "legendFormat": "non-heap" }
   ]
  }
 ]
}